/// Code generated by protocol.def.go; DO NOT EDIT.

package msg

import "gitlab.com/megatech/serverex/apps/excalibur/protocol/odm"

type AccountLoginRequest struct {
	Err ErrCode
}

type AccountLoginResponse struct {
	Err ErrCode
}

type AccountLogoutRequest struct {
	Err ErrCode
}

type AccountLogoutResponse struct {
	Err     ErrCode
	Message string `json:"message"`
}

type GetUserInfoRequest struct {
	Err ErrCode
}

type GetUserInfoResponse struct {
	Err  ErrCode
	User *odm.User `json:"user"`
}

type EnterDungeonRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
}

type EnterDungeonResponse struct {
	Err   ErrCode
	State string `json:"state"`
}

type ExitDungeonRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	IsSafeExit  bool   `json:"isSafeExit"`
}

type ExitDungeonResponse struct {
	Err            ErrCode
	State          string            `json:"state"`
	Gold           uint              `json:"gold"`
	StashGold      uint              `json:"stashGold"`
	DungeonGold    uint              `json:"dungeonGold"`
	DungeonExtGold uint              `json:"dungeonExtGold"`
	NpcList        []odm.Npc         `json:"npcList"`
	ItemList       []odm.Cell        `json:"itemList"`
	ItemPlainList  []odm.PlainCell   `json:"itemPlainList"`
	EquipmentsDiff []odm.LocatedCell `json:"equipmentsDiff"`
	BagDiff        []odm.LocatedCell `json:"bagDiff"`
	DungeonScore   odm.DungeonScore  `json:"dungeonScore"`
}

type RebornRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	Diamond     uint   `json:"diamond"`
}

type RebornResponse struct {
	Err     ErrCode
	State   string `json:"state"`
	Diamond uint   `json:"diamond"`
}

type EnterStageRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	StageId     int    `json:"stageId"`
}

type EnterStageResponse struct {
	Err       ErrCode
	State     string        `json:"state"`
	StageInfo odm.StageInfo `json:"stageInfo"`
}

type ExitStageRequest struct {
	Err               ErrCode
	CharacterId       string                       `json:"characterId"`
	StageId           int                          `json:"stageId"`
	StageClear        bool                         `json:"stageClear"`
	IsChapterEnding   bool                         `json:"isChapterEnding"`
	StageStat         odm.DungeonStageStat         `json:"stageStat"`
	AttributeSnapshot odm.DungeonAttributeSnapshot `json:"attributeSnapshot"`
}

type ExitStageResponse struct {
	Err         ErrCode
	State       string `json:"state"`
	BestStageId int    `json:"bestStageId"`
}

type BattleStartRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	NpcId       int    `json:"npcId"`
	NpcTypeId   int    `json:"npcTypeId"`
	LuckyValue  uint   `json:"luckyValue"`
}

type BattleStartResponse struct {
	Err    ErrCode
	ErrMsg string `json:"errMsg"`
	State  string `json:"state"`
}

type BattleEndRequest struct {
	Err          ErrCode
	CharacterId  string `json:"characterId"`
	NpcId        int    `json:"npcId"`
	NpcType      int    `json:"npcType"`
	BattleResult string `json:"battleResult"`
}

type BattleEndResponse struct {
	Err                ErrCode
	State              string            `json:"state"`
	KillValueIncreased uint              `json:"killValueIncreased"`
	KillValue          uint              `json:"killValue"`
	GoldIncreased      uint              `json:"goldIncreased"`
	GoldExtIncreased   uint              `json:"goldExtIncreased"`
	Gold               uint              `json:"gold"`
	UnpickupItems      []odm.Cell        `json:"unpickupItems"`
	AllAwardItems      []odm.Cell        `json:"allAwardItems"`
	BagDiff            []odm.LocatedCell `json:"bagDiff"`
}

type DestroyItemRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	CellIndex   int    `json:"cellIndex"`
}

type DestroyItemResponse struct {
	Err ErrCode
}

type ConsumItemRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	CellIndex   int    `json:"cellIndex"`
	Num         uint   `json:"num"`
}

type ConsumItemResponse struct {
	Err           ErrCode
	CellNewStatus odm.Cell `json:"cellNewStatus"`
}

type UseItemRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	TypeId      int    `json:"typeId"`
	Num         uint   `json:"num"`
}

type UseItemResponse struct {
	Err       ErrCode
	Diamond   uint              `json:"diamond"`
	Gold      uint              `json:"gold"`
	StashGold uint              `json:"stashGold"`
	BagDiff   []odm.LocatedCell `json:"bagDiff"`
}

type EquipRequest struct {
	Err           ErrCode
	CharacterId   string `json:"characterId"`
	FromCellIndex int    `json:"fromCellIndex"`
	ToCellIndex   int    `json:"toCellIndex"`
}

type EquipResponse struct {
	Err ErrCode
}

type UnequipRequest struct {
	Err           ErrCode
	CharacterId   string `json:"characterId"`
	FromCellIndex int    `json:"fromCellIndex"`
	ToCellIndex   int    `json:"toCellIndex"`
}

type UnequipResponse struct {
	Err ErrCode
}

type ListOnSaleRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
}

type ListOnSaleResponse struct {
	Err             ErrCode
	LastTime        int64            `json:"lastTime"`
	CurrentTime     int64            `json:"currentTime"`
	NextRefreshTime int64            `json:"nextRefreshTime"`
	OnSaleInfos     []odm.OnSaleInfo `json:"onSaleInfos"`
}

type RefreshOnSaleRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	CostGold    uint   `json:"costGold"`
	CostDiamond uint   `json:"costDiamond"`
}

type RefreshOnSaleResponse struct {
	Err     ErrCode
	Diamond uint `json:"diamond"`
}

type PurchaseRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	Guid        int64  `json:"guid"`
	GoodsId     int    `json:"goodsId"`
	TypeId      int    `json:"typeId"`
	Num         uint   `json:"num"`
	CostGold    uint   `json:"costGold"`
	CostDiamond uint   `json:"costDiamond"`
}

type PurchaseResponse struct {
	Err       ErrCode
	Gold      uint              `json:"gold"`
	StashGold uint              `json:"stashGold"`
	Diamond   uint              `json:"diamond"`
	BagDiff   []odm.LocatedCell `json:"bagDiff"`
}

type ListDiamondPriceRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
}

type ListDiamondPriceResponse struct {
	Err           ErrCode
	DiamondPrices []odm.DiamondPrice `json:"diamondPrices"`
}

type SubmitOrderRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	GoodsTypeId int    `json:"goodsTypeId"`
	Amount      uint   `json:"amount"`
	PayToken    string `json:"payToken"`
}

type SubmitOrderResponse struct {
	Err       ErrCode
	OrderInfo odm.OrderInfo `json:"orderInfo"`
}

type QueryOrderStatusRequest struct {
	Err     ErrCode
	OrderId string `json:"orderId"`
}

type QueryOrderStatusResponse struct {
	Err       ErrCode
	OrderInfo odm.OrderInfo `json:"orderInfo"`
}

type CraftRequest struct {
	Err           ErrCode
	CharacterId   string          `json:"characterId"`
	ToCraftTypeId int             `json:"toCraftTypeId"`
	Requires      []odm.PlainCell `json:"requires"`
	CostGold      uint            `json:"costGold"`
	CostDiamond   uint            `json:"costDiamond"`
}

type CraftResponse struct {
	Err          ErrCode
	CraftedItems odm.Cell          `json:"craftedItems"`
	Gold         uint              `json:"gold"`
	StashGold    uint              `json:"stashGold"`
	Diamond      uint              `json:"diamond"`
	BagDiff      []odm.LocatedCell `json:"bagDiff"`
}

type DecomposeRequest struct {
	Err                 ErrCode
	CharacterId         string `json:"characterId"`
	DecomposedCellIndex uint   `json:"decomposedCellIndex"`
	CostGold            uint   `json:"costGold"`
	CostDiamond         uint   `json:"costDiamond"`
}

type DecomposeResponse struct {
	Err       ErrCode
	TypeId    int               `json:"typeId"`
	Num       uint              `json:"num"`
	Gold      uint              `json:"gold"`
	StashGold uint              `json:"stashGold"`
	Diamond   uint              `json:"diamond"`
	BagDiff   []odm.LocatedCell `json:"bagDiff"`
}

type EnhanceRequest struct {
	Err            ErrCode
	CharacterId    string          `json:"characterId"`
	ToEnhanceIndex int             `json:"toEnhanceIndex"`
	CostGold       uint            `json:"costGold"`
	CostDiamond    uint            `json:"costDiamond"`
	Requires       []odm.PlainCell `json:"requires"`
}

type EnhanceResponse struct {
	Err          ErrCode
	EnhancedItem odm.Cell          `json:"enhancedItem"`
	Gold         uint              `json:"gold"`
	StashGold    uint              `json:"stashGold"`
	Diamond      uint              `json:"diamond"`
	BagDiff      []odm.LocatedCell `json:"bagDiff"`
}

type LevelUpRequest struct {
	Err          ErrCode
	CharacterId  string          `json:"characterId"`
	CurrentLevel int             `json:"currentLevel"`
	CostGold     uint            `json:"costGold"`
	Requires     []odm.PlainCell `json:"requires"`
}

type LevelUpResponse struct {
	Err          ErrCode
	CurrentLevel int               `json:"currentLevel"`
	Gold         uint              `json:"gold"`
	StashGold    uint              `json:"stashGold"`
	BagDiff      []odm.LocatedCell `json:"bagDiff"`
	RuneTree     odm.RuneTree      `json:"runeTree"`
}

type JobUpgradeRequest struct {
	Err           ErrCode
	CharacterId   string        `json:"characterId"`
	CostKillValue uint          `json:"costKillValue"`
	JobStatus     odm.JobStatus `json:"jobStatus"`
}

type JobUpgradeResponse struct {
	Err       ErrCode
	JobTree   odm.JobTree `json:"jobTree"`
	KillValue uint        `json:"killValue"`
}

type RuneEquipRequest struct {
	Err           ErrCode
	CharacterId   string `json:"characterId"`
	FromCellIndex int    `json:"fromCellIndex"`
	ToCellIndex   int    `json:"toCellIndex"`
}

type RuneEquipResponse struct {
	Err      ErrCode
	RuneTree odm.RuneTree      `json:"runeTree"`
	BagDiff  []odm.LocatedCell `json:"bagDiff"`
}

type RuneUnequipRequest struct {
	Err           ErrCode
	CharacterId   string `json:"characterId"`
	FromCellIndex int    `json:"fromCellIndex"`
}

type RuneUnequipResponse struct {
	Err       ErrCode
	CellIndex int               `json:"cellIndex"`
	RuneTree  odm.RuneTree      `json:"runeTree"`
	BagDiff   []odm.LocatedCell `json:"bagDiff"`
}

type ExpandBagCellRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	GoodsId     int    `json:"goodsId"`
}

type ExpandBagCellResponse struct {
	Err     ErrCode
	Start   int  `json:"start"`
	Offset  int  `json:"offset"`
	Diamond uint `json:"diamond"`
}

type PickupLootRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	From        []int  `json:"from"`
}

type PickupLootResponse struct {
	Err     ErrCode
	BagDiff []odm.LocatedCell `json:"bagDiff"`
}

type DestroyMultipleItemRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	CellIndices []int  `json:"cellIndices"`
}

type DestroyMultipleItemResponse struct {
	Err     ErrCode
	BagDiff []odm.LocatedCell `json:"bagDiff"`
}

type RefreshDiamondRequest struct {
	Err ErrCode
}

type RefreshDiamondResponse struct {
	Err     ErrCode
	Diamond uint `json:"diamond"`
}

type ListNoticeInfoRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
}

type ListNoticeInfoResponse struct {
	Err         ErrCode
	NoticeInfos []odm.NoticeInfo `json:"noticeInfos"`
}

type ConfirmNoticeInfoRequest struct {
	Err          ErrCode
	CharacterId  string `json:"characterId"`
	NoticeInfoId int    `json:"noticeInfoId"`
}

type ConfirmNoticeInfoResponse struct {
	Err       ErrCode
	BagGold   uint              `json:"bagGold"`
	StashGold uint              `json:"stashGold"`
	Diamond   uint              `json:"diamond"`
	BagDiff   []odm.LocatedCell `json:"bagDiff"`
}

type DeleteNoticeInfoRequest struct {
	Err          ErrCode
	CharacterId  string `json:"characterId"`
	NoticeInfoId int    `json:"noticeInfoId"`
}

type DeleteNoticeInfoResponse struct {
	Err ErrCode
}

type GetUserStatInfoRequest struct {
	Err ErrCode
}

type GetUserStatInfoResponse struct {
	Err      ErrCode
	StatInfo odm.StatInfo `json:"statInfo"`
}

type UserRenameRequest struct {
	Err     ErrCode
	NewName string `json:"newName"`
}

type UserRenameResponse struct {
	Err      ErrCode
	Nickname string `json:"nickname"`
	Diamond  uint   `json:"diamond"`
}

type PresentRedeemCodeRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	RedeemCode  string `json:"redeemCode"`
}

type PresentRedeemCodeResponse struct {
	Err        ErrCode
	AwardItems []odm.Cell        `json:"awardItems"`
	BagDiff    []odm.LocatedCell `json:"bagDiff"`
}

type MoveItemsStashToBagRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	Indices     []int  `json:"indices"`
}

type MoveItemsStashToBagResponse struct {
	Err       ErrCode
	StashDiff []odm.LocatedCell `json:"stashDiff"`
	BagDiff   []odm.LocatedCell `json:"bagDiff"`
}

type MoveItemsBagToStashRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	Indices     []int  `json:"indices"`
}

type MoveItemsBagToStashResponse struct {
	Err       ErrCode
	StashDiff []odm.LocatedCell `json:"stashDiff"`
	BagDiff   []odm.LocatedCell `json:"bagDiff"`
}

type MoveGoldStashToBagRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	Gold        uint   `json:"gold"`
}

type MoveGoldStashToBagResponse struct {
	Err       ErrCode
	BagGold   uint `json:"bagGold"`
	StashGold uint `json:"stashGold"`
}

type MoveGoldBagToStashRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	Gold        uint   `json:"gold"`
}

type MoveGoldBagToStashResponse struct {
	Err       ErrCode
	BagGold   uint `json:"bagGold"`
	StashGold uint `json:"stashGold"`
}

type DestroyItemsInStashRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	Indices     []int  `json:"indices"`
}

type DestroyItemsInStashResponse struct {
	Err       ErrCode
	StashDiff []odm.LocatedCell `json:"stashDiff"`
}

type SortItemsInStashRequest struct {
	Err ErrCode
}

type SortItemsInStashResponse struct {
	Err       ErrCode
	StashDiff []odm.LocatedCell `json:"stashDiff"`
}

type ExpandStashCellRequest struct {
	Err ErrCode
}

type ExpandStashCellResponse struct {
	Err     ErrCode
	Start   int  `json:"start"`
	Offset  int  `json:"offset"`
	Diamond uint `json:"diamond"`
}

type OpenBoxRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	TypeId      int    `json:"typeId"`
}

type OpenBoxResponse struct {
	Err           ErrCode
	UnpickupItems []odm.Cell        `json:"unpickupItems"`
	AllAwardItems []odm.Cell        `json:"allAwardItems"`
	BagDiff       []odm.LocatedCell `json:"bagDiff"`
}

type SortItemsInBagRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
}

type SortItemsInBagResponse struct {
	Err     ErrCode
	BagDiff []odm.LocatedCell `json:"bagDiff"`
}

type MarkAsReadNoticeInfoRequest struct {
	Err          ErrCode
	CharacterId  string `json:"characterId"`
	NoticeInfoId int    `json:"noticeInfoId"`
}

type MarkAsReadNoticeInfoResponse struct {
	Err ErrCode
}

type GetExploreInfoRequest struct {
	Err ErrCode
}

type GetExploreInfoResponse struct {
	Err         ErrCode
	ServerTime  int64           `json:"serverTime"`
	ExploreInfo odm.ExploreInfo `json:"exploreInfo"`
}

type AddExploreChargeCountRequest struct {
	Err   ErrCode
	Count int `json:"count"`
}

type AddExploreChargeCountResponse struct {
	Err         ErrCode
	ServerTime  int64           `json:"serverTime"`
	Diamond     uint            `json:"diamond"`
	ExploreInfo odm.ExploreInfo `json:"exploreInfo"`
}

type ReduceExploreTimeRequest struct {
	Err            ErrCode
	CharacterId    string `json:"characterId"`
	ExploreStageId int    `json:"exploreStageId"`
	ReduceTime     int64  `json:"reduceTime"`
}

type ReduceExploreTimeResponse struct {
	Err         ErrCode
	ServerTime  int64           `json:"serverTime"`
	Diamond     uint            `json:"diamond"`
	ExploreInfo odm.ExploreInfo `json:"exploreInfo"`
}

type ExploreStartRequest struct {
	Err            ErrCode
	CharacterId    string `json:"characterId"`
	ExploreStageId int    `json:"exploreStageId"`
}

type ExploreStartResponse struct {
	Err         ErrCode
	ExploreInfo odm.ExploreInfo `json:"exploreInfo"`
}

type ExploreViewAwardRequest struct {
	Err            ErrCode
	CharacterId    string `json:"characterId"`
	ExploreStageId int    `json:"exploreStageId"`
}

type ExploreViewAwardResponse struct {
	Err   ErrCode
	Award []odm.PlainCell `json:"award"`
}

type ExploreEndRequest struct {
	Err                ErrCode
	CharacterId        string `json:"characterId"`
	ExploreCharacterId string `json:"exploreCharacterId"`
	ExploreStageId     int    `json:"exploreStageId"`
}

type ExploreEndResponse struct {
	Err         ErrCode
	ExploreInfo odm.ExploreInfo   `json:"exploreInfo"`
	AwardItems  []odm.Cell        `json:"awardItems"`
	BagDiff     []odm.LocatedCell `json:"bagDiff"`
}

type PuzzleStartRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	StageId     int    `json:"stageId"`
	RandomSeed  int    `json:"randomSeed"`
	Total       int    `json:"total"`
}

type PuzzleStartResponse struct {
	Err ErrCode
}

type PuzzleUpdateProcessRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	StageId     int    `json:"stageId"`
	Process     int    `json:"process"`
}

type PuzzleUpdateProcessResponse struct {
	Err ErrCode
}

type PuzzleEndRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	StageId     int    `json:"stageId"`
	Selected    int    `json:"selected"`
}

type PuzzleEndResponse struct {
	Err ErrCode
}

type ActiveNewCharacterRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	HeroId      int    `json:"heroId"`
}

type ActiveNewCharacterResponse struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	Diamond     uint   `json:"diamond"`
	Gold        uint   `json:"gold"`
	StashGold   uint   `json:"stashGold"`
}

type KillCharacterRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
}

type KillCharacterResponse struct {
	Err     ErrCode
	State   string            `json:"state"`
	BagDiff []odm.LocatedCell `json:"bagDiff"`
}

type GetDungeonRankingInfoRequest struct {
	Err       ErrCode
	ChapterId int `json:"chapterId"`
}

type GetDungeonRankingInfoResponse struct {
	Err  ErrCode
	Info odm.DungeonRankingInfo `json:"info"`
}

type GetDungeonRankingListRequest struct {
	Err       ErrCode
	ChapterId int `json:"chapterId"`
	IndexFrom int `json:"indexFrom"`
	Count     int `json:"count"`
}

type GetDungeonRankingListResponse struct {
	Err  ErrCode
	Info []odm.DungeonRankingInfo `json:"info"`
}

type GetPersonalRankingInfoRequest struct {
	Err         ErrCode
	RankingType string `json:"rankingType"`
}

type GetPersonalRankingInfoResponse struct {
	Err  ErrCode
	Info odm.PersonalRankingInfo `json:"info"`
}

type GetPersonalRankingListRequest struct {
	Err         ErrCode
	RankingType string `json:"rankingType"`
	IndexFrom   int    `json:"indexFrom"`
	Count       int    `json:"count"`
}

type GetPersonalRankingListResponse struct {
	Err  ErrCode
	Info []odm.PersonalRankingInfo `json:"info"`
}

type GetThreadCommentRequest struct {
	Err       ErrCode
	ThreadId  int64 `json:"threadId"`
	IndexFrom int   `json:"indexFrom"`
	Count     int   `json:"count"`
}

type GetThreadCommentResponse struct {
	Err      ErrCode
	Comments []odm.Comment `json:"comments"`
}

type GetThreadHotCommentRequest struct {
	Err      ErrCode
	ThreadId int64 `json:"threadId"`
	TopN     int   `json:"topN"`
}

type GetThreadHotCommentResponse struct {
	Err      ErrCode
	Comments []odm.Comment `json:"comments"`
}

type GetHeroThreadIdRequest struct {
	Err    ErrCode
	HeroId int `json:"heroId"`
}

type GetHeroThreadIdResponse struct {
	Err      ErrCode
	ThreadId int64 `json:"threadId"`
}

type PostCommentRequest struct {
	Err      ErrCode
	ThreadId int64  `json:"threadId"`
	Content  string `json:"content"`
}

type PostCommentResponse struct {
	Err ErrCode
}

type PraiseThreadRequest struct {
	Err      ErrCode
	ThreadId int64 `json:"threadId"`
}

type PraiseThreadResponse struct {
	Err ErrCode
}

type PraiseCommentRequest struct {
	Err       ErrCode
	ThreadId  int64 `json:"threadId"`
	CommentId int64 `json:"commentId"`
}

type PraiseCommentResponse struct {
	Err ErrCode
}

type GetUserPropertiesRequest struct {
	Err ErrCode
	Key string `json:"key"`
}

type GetUserPropertiesResponse struct {
	Err ErrCode
	Doc string `json:"doc"`
}

type SetUserPropertiesRequest struct {
	Err ErrCode
	Key string `json:"key"`
	Doc string `json:"doc"`
}

type SetUserPropertiesResponse struct {
	Err ErrCode
}

type GetAchievementAwardRequest struct {
	Err           ErrCode
	CharacterId   string `json:"characterId"`
	AchievementId int    `json:"achievementId"`
}

type GetAchievementAwardResponse struct {
	Err              ErrCode
	AchievementScore uint              `json:"achievementScore"`
	BagDiff          []odm.LocatedCell `json:"bagDiff"`
	Diamond          uint              `json:"diamond"`
	Gold             uint              `json:"gold"`
}

type GetOperationActivityInfoRequest struct {
	Err ErrCode
}

type GetOperationActivityInfoResponse struct {
	Err               ErrCode
	ServerTime        int64                 `json:"serverTime"`
	OperationActivity odm.OperationActivity `json:"operationActivity"`
}

type GetActivtyAwardFisrtPayRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
}

type GetActivtyAwardFisrtPayResponse struct {
	Err         ErrCode
	ActivityId  int                     `json:"activityId"`
	ProcessInfo odm.ActivityProcessInfo `json:"processInfo"`
	BagDiff     []odm.LocatedCell       `json:"bagDiff"`
	Diamond     uint                    `json:"diamond"`
	Gold        uint                    `json:"gold"`
}

type GetActivtyAwardSignInFirst7DayRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
}

type GetActivtyAwardSignInFirst7DayResponse struct {
	Err         ErrCode
	ActivityId  int                     `json:"activityId"`
	ProcessInfo odm.ActivityProcessInfo `json:"processInfo"`
	BagDiff     []odm.LocatedCell       `json:"bagDiff"`
	Diamond     uint                    `json:"diamond"`
	Gold        uint                    `json:"gold"`
}

type GetActivtyAwardSignIn30DayRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
}

type GetActivtyAwardSignIn30DayResponse struct {
	Err         ErrCode
	ActivityId  int                     `json:"activityId"`
	ProcessInfo odm.ActivityProcessInfo `json:"processInfo"`
	BagDiff     []odm.LocatedCell       `json:"bagDiff"`
	Diamond     uint                    `json:"diamond"`
	Gold        uint                    `json:"gold"`
}

type GetDungeonRule1Request struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
}

type GetDungeonRule1Response struct {
	Err     ErrCode
	BagDiff []odm.LocatedCell `json:"bagDiff"`
}

type GetDungeonRule2Request struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	Level       int    `json:"level"`
	IsEquiped   bool   `json:"isEquiped"`
	CellIndex   int    `json:"cellIndex"`
}

type GetDungeonRule2Response struct {
	Err            ErrCode
	BagDiff        []odm.LocatedCell `json:"bagDiff"`
	EquipmentsDiff []odm.LocatedCell `json:"equipmentsDiff"`
}

type GetVipInfoRequest struct {
	Err ErrCode
}

type GetVipInfoResponse struct {
	Err        ErrCode
	ServerTime int64       `json:"serverTime"`
	VipInfo    odm.VipInfo `json:"vipInfo"`
}

type VipYueKaMaterialGetAwardRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
}

type VipYueKaMaterialGetAwardResponse struct {
	Err     ErrCode
	Diamond uint              `json:"diamond"`
	BagDiff []odm.LocatedCell `json:"bagDiff"`
}

type PayGetCallbackUrlRequest struct {
	Err ErrCode
}

type PayGetCallbackUrlResponse struct {
	Err ErrCode
}

type PayPrepareRequest struct {
	Err ErrCode
}

type PayPrepareResponse struct {
	Err ErrCode
}

type PayVerifyReceiptRequest struct {
	Err ErrCode
}

type PayVerifyReceiptResponse struct {
	Err ErrCode
}

type PayAppleVerifyReceiptRequest struct {
	Err         ErrCode
	UseSandbox  bool   `json:"useSandbox"`
	Receipt     string `json:"receipt"`
	Uid         int64  `json:"uid"`
	DeviceToken string `json:"deviceToken"`
}

type PayAppleVerifyReceiptResponse struct {
	Err     ErrCode
	OrderId int    `json:"orderId"`
	Diamond uint   `json:"diamond"`
	SkuType string `json:"skuType"`
}

type PayVerifyOrderRequest struct {
	Err ErrCode
}

type PayVerifyOrderResponse struct {
	Err ErrCode
}

type PayListOrderRequest struct {
	Err ErrCode
}

type PayListOrderResponse struct {
	Err ErrCode
}

type PayGooglePurchaseRequest struct {
	Err          ErrCode
	PurchaseInfo string `json:"purchaseInfo"`
}

type PayGooglePurchaseResponse struct {
	Err          ErrCode
	GoogleErrMsg string `json:"googleErrMsg"`
}

type PayGoogleConsumeRequest struct {
	Err           ErrCode
	OrderId       string `json:"orderId"`
	PackageName   string `json:"packageName"`
	ProductId     string `json:"productId"`
	PurchaseToken string `json:"purchaseToken"`
}

type PayGoogleConsumeResponse struct {
	Err          ErrCode
	GoogleErrMsg string `json:"googleErrMsg"`
}

type GM_ActivateUserRequest struct {
	Err ErrCode
}

type GM_ActivateUserResponse struct {
	Err ErrCode
}

type GM_ResetUserRequest struct {
	Err ErrCode
}

type GM_ResetUserResponse struct {
	Err ErrCode
}

type GM_CreateItemRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	TypeId      int    `json:"typeId"`
	StarLevel   int    `json:"starLevel"`
	Num         uint   `json:"num"`
}

type GM_CreateItemResponse struct {
	Err       ErrCode
	NewItem   odm.Item `json:"newItem"`
	Num       uint     `json:"num"`
	CellIndex int      `json:"cellIndex"`
}

type GM_SetMyMoneyRequest struct {
	Err     ErrCode
	Gold    uint `json:"gold"`
	Diamond uint `json:"diamond"`
}

type GM_SetMyMoneyResponse struct {
	Err ErrCode
}

type GM_ResetJobRequest struct {
	Err         ErrCode
	CharacterId string `json:"characterId"`
	KillValue   uint   `json:"killValue"`
}

type GM_ResetJobResponse struct {
	Err       ErrCode
	JobTree   odm.JobTree `json:"jobTree"`
	KillValue uint        `json:"killValue"`
}

type GM_SetVipInfoRequest struct {
	Err     ErrCode
	VipInfo odm.VipInfo `json:"vipInfo"`
}

type GM_SetVipInfoResponse struct {
	Err ErrCode
}
