
[AccountOption]

[GateHttpOption]
  DevModeEnable = false
  ListenAddress = "127.0.0.1:20002"
  UseTLS = true

[MongodbOption]
  MongoAddress = "mongodb://127.0.0.1:27017/excalibur_taptap"
