/// Code generated by protocol.def.go; DO NOT EDIT.

package odm

type User struct {
	Uid                  int64                `json:"uid" bson:"uid"`
	Nickname             string               `json:"nickname" bson:"nickname"`
	CreatedAt            string               `json:"createdAt" bson:"createdAt"`
	UpdatedAt            string               `json:"updatedAt" bson:"updatedAt"`
	CreateAtUnix         int64                `json:"createAtUnix" bson:"createAtUnix"`
	UpdatedAtUnix        int64                `json:"updatedAtUnix" bson:"updatedAtUnix"`
	CharacterIds         []string             `json:"characterIds" bson:"characterIds"`
	Characters           map[string]Character `json:"characters" bson:"characters"`
	Stash                Stash                `json:"stash" bson:"stash"`
	Diamond              uint                 `json:"diamond" bson:"diamond"`
	VipInfo              VipInfo              `json:"vipInfo" bson:"vipInfo"`
	OnSaleInfos          []OnSaleInfo         `json:"onSaleInfos" bson:"onSaleInfos"`
	OnSaleLastUpdateTime int64                `json:"onSaleLastUpdateTime" bson:"onSaleLastUpdateTime"`
	RankingInfo          RankingInfo          `json:"rankingInfo" bson:"rankingInfo"`
	StatInfo             StatInfo             `json:"statInfo" bson:"statInfo"`
	ExploreInfo          ExploreInfo          `json:"exploreInfo" bson:"exploreInfo"`
	BestDungeonRanking   []DungeonRankingInfo `json:"bestDungeonRanking" bson:"bestDungeonRanking"`
	OperationActivity    OperationActivity    `json:"operationActivity" bson:"operationActivity"`
}

type VipInfo struct {
	IsVip_Godbless                 bool  `json:"isVip_Godbless" bson:"isVip_Godbless"`
	Vip_YueKa_Material_ExpireTime  int64 `json:"vip_YueKa_Material_ExpireTime" bson:"vip_YueKa_Material_ExpireTime"`
	Vip_YueKa_Material_LastGetTime int64 `json:"vip_YueKa_Material_LastGetTime" bson:"vip_YueKa_Material_LastGetTime"`
}

type Character struct {
	HeroId          int           `json:"heroId" bson:"heroId"`
	Level           int           `json:"level" bson:"level"`
	Gold            uint          `json:"gold" bson:"gold"`
	BattleAttribute Attribute     `json:"battleAttribute" bson:"battleAttribute"`
	RankingInfo     RankingInfo   `json:"rankingInfo" bson:"rankingInfo"`
	DungeonStatus   DungeonStatus `json:"dungeonStatus" bson:"dungeonStatus"`
	RuneTree        RuneTree      `json:"runeTree" bson:"runeTree"`
	Bag             Bag           `json:"bag" bson:"bag"`
}

type Attribute struct {
	Hp         int     `json:"hp" bson:"hp"`
	Mp         int     `json:"mp" bson:"mp"`
	KillValue  uint    `json:"killValue" bson:"killValue"`
	JobTree    JobTree `json:"jobTree" bson:"jobTree"`
	LuckyValue uint    `json:"luckyValue" bson:"luckyValue"`
}

type JobTree struct {
	JobStatus []JobStatus `json:"jobStatus" bson:"jobStatus"`
}

type JobStatus struct {
	JobId   int  `json:"jobId" bson:"jobId"`
	JobStar uint `json:"jobStar" bson:"jobStar"`
}

type RuneTree struct {
	Cells []RuneCell `json:"cells" bson:"cells"`
}

type RuneCell struct {
	Item      *Item `json:"item" bson:"item"`
	SlotColor int   `json:"slotColor" bson:"slotColor"`
	Enable    bool  `json:"enable" bson:"enable"`
}

type Bag struct {
	Equipments []Cell `json:"equipments" bson:"equipments"`
	Cells      []Cell `json:"cells" bson:"cells"`
}

type Stash struct {
	Gold  uint   `json:"gold" bson:"gold"`
	Cells []Cell `json:"cells" bson:"cells"`
}

type Cell struct {
	Num  uint  `json:"num" bson:"num"`
	Item *Item `json:"item" bson:"item"`
}

type Item struct {
	Guid            int64 `json:"guid" bson:"guid"`
	TypeId          int   `json:"typeId" bson:"typeId"`
	StarLevel       int   `json:"starLevel" bson:"starLevel"`
	StarUpgradeInfo []int `json:"starUpgradeInfo" bson:"starUpgradeInfo"`
	Fresh           bool  `json:"fresh" bson:"fresh"`
}

type StageInfo struct {
	StageId      int        `json:"stageId" bson:"stageId"`
	MapId        int        `json:"mapId" bson:"mapId"`
	EntranceType int        `json:"entranceType" bson:"entranceType"`
	Seed         int        `json:"seed" bson:"seed"`
	NpcList      []Npc      `json:"npcList" bson:"npcList"`
	BoxList      []Box      `json:"boxList" bson:"boxList"`
	PuzzleInfo   PuzzleInfo `json:"puzzleInfo" bson:"puzzleInfo"`
}

type Npc struct {
	NpcId     int  `json:"npcId" bson:"npcId"`
	NpcTypeId int  `json:"npcTypeId" bson:"npcTypeId"`
	IsDead    bool `json:"isDead" bson:"isDead"`
}

type Box struct {
	Id       int  `json:"id" bson:"id"`
	TypeId   int  `json:"typeId" bson:"typeId"`
	IsOpened bool `json:"isOpened" bson:"isOpened"`
}

type DungeonStatus struct {
	EnterAt           int64                    `json:"enterAt" bson:"enterAt"`
	State             string                   `json:"state" bson:"state"`
	StageProgress     []StageInfo              `json:"stageProgress" bson:"stageProgress"`
	CurrentStageInfo  StageInfo                `json:"currentStageInfo" bson:"currentStageInfo"`
	CurrentBattleNpc  Npc                      `json:"currentBattleNpc" bson:"currentBattleNpc"`
	KilledNpcList     []Npc                    `json:"killedNpcList" bson:"killedNpcList"`
	OpenBoxList       []Npc                    `json:"openBoxList" bson:"openBoxList"`
	UnpickedLoot      []Cell                   `json:"unpickedLoot" bson:"unpickedLoot"`
	LootTotal         []Cell                   `json:"lootTotal" bson:"lootTotal"`
	GoldTotal         uint                     `json:"goldTotal" bson:"goldTotal"`
	GoldExtTotal      uint                     `json:"goldExtTotal" bson:"goldExtTotal"`
	AttributeSnapshot DungeonAttributeSnapshot `json:"attributeSnapshot" bson:"attributeSnapshot"`
	StageStat         DungeonStageStat         `json:"stageStat" bson:"stageStat"`
}

type OnSaleInfo struct {
	Guid             int64 `json:"guid" bson:"guid"`
	GoodsId          int   `json:"goodsId" bson:"goodsId"`
	TypeId           int   `json:"typeId" bson:"typeId"`
	NumTotal         uint  `json:"numTotal" bson:"numTotal"`
	NumAvailable     uint  `json:"numAvailable" bson:"numAvailable"`
	NumSQ            uint  `json:"numSQ" bson:"numSQ"`
	AvailableStageId int   `json:"availableStageId" bson:"availableStageId"`
	CostGold         uint  `json:"costGold" bson:"costGold"`
	CostDiamond      uint  `json:"costDiamond" bson:"costDiamond"`
	Discount         uint  `json:"discount" bson:"discount"`
}

type DiamondPrice struct {
	GoodsId  int  `json:"goodsId" bson:"goodsId"`
	Num      uint `json:"num" bson:"num"`
	PriceRMB uint `json:"priceRMB" bson:"priceRMB"`
	Discount uint `json:"discount" bson:"discount"`
}

type OrderInfo struct {
	OrderId         string `json:"orderId" bson:"orderId"`
	GoodsTypeId     int    `json:"goodsTypeId" bson:"goodsTypeId"`
	Amount          uint   `json:"amount" bson:"amount"`
	PayToken        string `json:"payToken" bson:"payToken"`
	TradeSubmitTime int64  `json:"tradeSubmitTime" bson:"tradeSubmitTime"`
	TradeDealTime   int64  `json:"tradeDealTime" bson:"tradeDealTime"`
}

type PlainCell struct {
	TypeId int  `json:"typeId" bson:"typeId"`
	Num    uint `json:"num" bson:"num"`
}

type LocatedCell struct {
	Index int  `json:"index" bson:"index"`
	Cell  Cell `json:"cell" bson:"cell"`
}

type RankingInfo struct {
	BestStageId int `json:"bestStageId" bson:"bestStageId"`
}

type NoticeInfo struct {
	Id        int    `json:"id" bson:"id"`
	Read      bool   `json:"read" bson:"read"`
	Confirmed bool   `json:"confirmed" bson:"confirmed"`
	Deleted   bool   `json:"deleted" bson:"deleted"`
	SendTime  int64  `json:"sendTime" bson:"sendTime"`
	Title     string `json:"title" bson:"title"`
	Sender    string `json:"sender" bson:"sender"`
	Content   string `json:"content" bson:"content"`
	Gold      uint   `json:"gold" bson:"gold"`
	Diamond   uint   `json:"diamond" bson:"diamond"`
	Gift      []Cell `json:"gift" bson:"gift"`
}

type UserNoticeInfo struct {
	Uid         int64        `json:"uid" bson:"uid"`
	NoticeInfos []NoticeInfo `json:"noticeInfos" bson:"noticeInfos"`
}

type StatInfo struct {
	CreateTime          int64 `json:"createTime" bson:"createTime"`
	LoginDaysTotal      uint  `json:"loginDaysTotal" bson:"loginDaysTotal"`
	LastLoginTime       int64 `json:"lastLoginTime" bson:"lastLoginTime"`
	DeadTimes           uint  `json:"deadTimes" bson:"deadTimes"`
	AchievementScore    uint  `json:"achievementScore" bson:"achievementScore"`
	AwardItemCount      uint  `json:"awardItemCount" bson:"awardItemCount"`
	KillMonsterCount    uint  `json:"killMonsterCount" bson:"killMonsterCount"`
	HuoDeChengZhuangShu uint  `json:"huoDeChengZhuangShu" bson:"huoDeChengZhuangShu"`
}

type ExploreInfo struct {
	LastRefreshChargeTime int64            `json:"lastRefreshChargeTime" bson:"lastRefreshChargeTime"`
	ChargeAvailable       int              `json:"chargeAvailable" bson:"chargeAvailable"`
	ChargeTotal           int              `json:"chargeTotal" bson:"chargeTotal"`
	Status                []*ExploreStatus `json:"status" bson:"status"`
}

type ExploreStatus struct {
	CharacterId    string `json:"characterId" bson:"characterId"`
	HeroId         int    `json:"heroId" bson:"heroId"`
	IsExploring    bool   `json:"isExploring" bson:"isExploring"`
	ExploreStageId int    `json:"exploreStageId" bson:"exploreStageId"`
	DispatchedAt   int64  `json:"dispatchedAt" bson:"dispatchedAt"`
	CompleteAt     int64  `json:"completeAt" bson:"completeAt"`
}

type PuzzleInfo struct {
	RandomSeed int `json:"randomSeed" bson:"randomSeed"`
	Total      int `json:"total" bson:"total"`
	Process    int `json:"process" bson:"process"`
	Selected   int `json:"selected" bson:"selected"`
}

type DungeonStageStat struct {
	Damage  int  `json:"damage" bson:"damage"`
	Healing int  `json:"healing" bson:"healing"`
	Kill    uint `json:"kill" bson:"kill"`
}

type DungeonAttributeSnapshot struct {
	Hp        uint `json:"hp" bson:"hp"`
	Mp        uint `json:"mp" bson:"mp"`
	MinAttack uint `json:"minAttack" bson:"minAttack"`
	MaxAttack uint `json:"maxAttack" bson:"maxAttack"`
	MinDef    uint `json:"minDef" bson:"minDef"`
	MaxDef    uint `json:"maxDef" bson:"maxDef"`
	HeroLevel uint `json:"heroLevel" bson:"heroLevel"`
	GearScore int  `json:"gearScore" bson:"gearScore"`
}

type DungeonScore struct {
	BestStageId      int   `json:"bestStageId" bson:"bestStageId"`
	OpenBoxScore     int   `json:"openBoxScore" bson:"openBoxScore"`
	KillMonsterScore int   `json:"killMonsterScore" bson:"killMonsterScore"`
	HealthScore      int   `json:"healthScore" bson:"healthScore"`
	GearScore        int   `json:"gearScore" bson:"gearScore"`
	KillBossScore    int   `json:"killBossScore" bson:"killBossScore"`
	AwardItemScore   int   `json:"awardItemScore" bson:"awardItemScore"`
	TimeCost         int64 `json:"timeCost" bson:"timeCost"`
}

type DungeonRankingInfo struct {
	Uid               int64                    `json:"uid" bson:"uid"`
	CharacterId       string                   `json:"characterId" bson:"characterId"`
	Nickname          string                   `json:"nickname" bson:"nickname"`
	Time              int64                    `json:"time" bson:"time"`
	Date              int64                    `json:"date" bson:"date"`
	Rank              int                      `json:"rank" bson:"rank"`
	ChapterId         int                      `json:"chapterId" bson:"chapterId"`
	AttributeSnapshot DungeonAttributeSnapshot `json:"attributeSnapshot" bson:"attributeSnapshot"`
	StageStat         DungeonStageStat         `json:"stageStat" bson:"stageStat"`
	Equipments        []Cell                   `json:"equipments" bson:"equipments"`
	JobTree           JobTree                  `json:"jobTree" bson:"jobTree"`
	ThreadId          int64                    `json:"threadId" bson:"threadId"`
}

type PersonalRankingInfo struct {
	Uid         int64  `json:"uid" bson:"uid"`
	Nickname    string `json:"nickname" bson:"nickname"`
	Date        int64  `json:"date" bson:"date"`
	Rank        int    `json:"rank" bson:"rank"`
	Gold        uint   `json:"gold" bson:"gold"`
	Kill        uint   `json:"kill" bson:"kill"`
	Achievement uint   `json:"achievement" bson:"achievement"`
	ThreadId    int64  `json:"threadId" bson:"threadId"`
}

type Comment struct {
	ThreadId  int64  `json:"threadId" bson:"threadId"`
	CommentId int64  `json:"commentId" bson:"commentId"`
	Uid       int64  `json:"uid" bson:"uid"`
	Date      int64  `json:"date" bson:"date"`
	Nickname  string `json:"nickname" bson:"nickname"`
	Praise    int    `json:"praise" bson:"praise"`
	Content   string `json:"content" bson:"content"`
}

type OperationActivity struct {
	FisrtPay        ActivityProcessInfo `json:"fisrtPay" bson:"fisrtPay"`
	SignInFirst7Day ActivityProcessInfo `json:"signInFirst7Day" bson:"signInFirst7Day"`
	SignIn30Day     ActivityProcessInfo `json:"signIn30Day" bson:"signIn30Day"`
}

type ActivityProcessInfo struct {
	Process     int   `json:"process" bson:"process"`
	LastGetTime int64 `json:"lastGetTime" bson:"lastGetTime"`
}
