// Code generated by "stringer -type=CodeType"; DO NOT EDIT.

package pkt

import "strconv"

const _CodeType_name = "C_EchoC_HandshakeC_TimeSyncC_ErrorC_Message"

var _CodeType_index = [...]uint8{0, 6, 17, 27, 34, 43}

func (i CodeType) String() string {
	i -= 1
	if i >= CodeType(len(_CodeType_index)-1) {
		return "CodeType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _CodeType_name[_CodeType_index[i]:_CodeType_index[i+1]]
}
