/// Code generated by odm.go; DO NOT EDIT.

using System.Collections.Generic;

namespace ExcaliburNetwork.Protocol {

	public class User {
		public long uid;
		public string nickname;
		public string createdAt;
		public string updatedAt;
		public List<string> characterIds = new List<string>();
		public Dictionary<string, Character> characters = new Dictionary<string, Character>();
		public Stash stash;
		public int money;
	}

	public class Character {
		public int heroId;
		public int level;
		public Attribute townAttribute;
		public StageInfo stageProgress;
		public StageInfo lastStageInfo;
		public MapInfo lastMapInfo;
		public Bag bag;
		public Attribute battleAttribute;
	}

	public class Attribute {
		public int hp;
		public int mp;
		public int killValue;
		public int jobId;
		public int jobLevel;
		public int jobStar;
		public JobTree jobTree;
		public int luckyValue;
		public int extraGold;
	}

	public class JobTree {
		public List<int> jobIds = new List<int>();
	}

	public class Bag {
		public List<Cell> equipments = new List<Cell>();
		public int cellsCapacity;
		public List<Cell> cells = new List<Cell>();
	}

	public class Stash {
		public int cellsCapacity;
		public List<Cell> cells = new List<Cell>();
	}

	public class Cell {
		public int index;
		public int num;
		public Item item;
	}

	public class Item {
		public long guid;
		public int typeId;
		public int level;
		public bool fresh;
	}

	public class StageInfo {
		public int chapterId;
		public int stageId;
	}

	public class MapInfo {
		public int mapId;
		public int mapType;
		public int seed;
		public List<Npc> npcList = new List<Npc>();
	}

	public class Npc {
		public int npcId;
		public int npcTypeId;
		public bool isDead;
	}

}
