
[[ServiceList]]
  Endpoint = "https://datacenter.53site.com/excalibur/assets/0.0.1/"
  Env = "all"
  ServerId = "assets"
  ServiceType = "assets"
  Version = "0.0.1"

[[ServiceList]]
  Endpoint = "https://excalibur.53site.com/excalibur/beta/api/gs"
  Env = "beta"
  ServerId = "test-node-01"
  ServiceType = "game"
  Version = "0.0.1"

[[ServiceList]]
  Endpoint = "https://excalibur.53site.com/excalibur/approval/api/gs"
  Env = "approval"
  ServerId = "game-node-01"
  ServiceType = "game"
  Version = "1.0.1"

[[ServiceList]]
  Endpoint = "https://excalibur.53site.com/excalibur/prod/api/gs"
  Env = "prod"
  ServerId = "game-node-01"
  ServiceType = "game"
  Version = "1.0.1"
