// Code generated by "stringer -type=CodeType"; DO NOT EDIT.

package msg

import "strconv"

const _CodeType_name = "C_MulticastC_AnyC_InvalidC_AgentConnectC_AgentDisconnectC_AgentInactiveC_AgentDeactive"

var _CodeType_index = [...]uint8{0, 11, 16, 25, 39, 56, 71, 86}

func (i CodeType) String() string {
	i -= -2
	if i < 0 || i >= CodeType(len(_CodeType_index)-1) {
		return "CodeType(" + strconv.FormatInt(int64(i+-2), 10) + ")"
	}
	return _CodeType_name[_CodeType_index[i]:_CodeType_index[i+1]]
}
