/// Code generated by protocol.def.go; DO NOT EDIT.

using System.Collections.Generic;

namespace Network.sdk.Excalibur.Protocol
{
    public class User
    {
    	public long uid;
    	public string nickname;
    	public string createdAt;
    	public string updatedAt;
    	public long createAtUnix;
    	public long updatedAtUnix;
    	public List<string> characterIds = new List<string>();
    	public Dictionary<string, Character> characters = new Dictionary<string, Character>();
    	public Stash stash;
    	public uint diamond;
    	public VipInfo vipInfo;
    	public List<OnSaleInfo> onSaleInfos = new List<OnSaleInfo>();
    	public long onSaleLastUpdateTime;
    	public RankingInfo rankingInfo;
    	public StatInfo statInfo;
    	public ExploreInfo exploreInfo;
    	public List<DungeonRankingInfo> bestDungeonRanking = new List<DungeonRankingInfo>();
    	public OperationActivity operationActivity;
    }

    public class VipInfo
    {
    	public bool isVip_Godbless;
    	public long vip_YueKa_Material_ExpireTime;
    	public long vip_YueKa_Material_LastGetTime;
    }

    public class Character
    {
    	public int heroId;
    	public int level;
    	public uint gold;
    	public Attribute battleAttribute;
    	public RankingInfo rankingInfo;
    	public DungeonStatus dungeonStatus;
    	public RuneTree runeTree;
    	public Bag bag;
    }

    public class Attribute
    {
    	public int hp;
    	public int mp;
    	public uint killValue;
    	public JobTree jobTree;
    	public uint luckyValue;
    }

    public class JobTree
    {
    	public List<JobStatus> jobStatus = new List<JobStatus>();
    }

    public class JobStatus
    {
    	public int jobId;
    	public uint jobStar;
    }

    public class RuneTree
    {
    	public List<RuneCell> cells = new List<RuneCell>();
    }

    public class RuneCell
    {
    	public Item item;
    	public int slotColor;
    	public bool enable;
    }

    public class Bag
    {
    	public List<Cell> equipments = new List<Cell>();
    	public List<Cell> cells = new List<Cell>();
    }

    public class Stash
    {
    	public uint gold;
    	public List<Cell> cells = new List<Cell>();
    }

    public class Cell
    {
    	public uint num;
    	public Item item;
    }

    public class Item
    {
    	public long guid;
    	public int typeId;
    	public int starLevel;
    	public List<int> starUpgradeInfo = new List<int>();
    	public bool fresh;
    }

    public class StageInfo
    {
    	public int stageId;
    	public int mapId;
    	public int entranceType;
    	public int seed;
    	public List<Npc> npcList = new List<Npc>();
    	public List<Box> boxList = new List<Box>();
    	public PuzzleInfo puzzleInfo;
    }

    public class Npc
    {
    	public int npcId;
    	public int npcTypeId;
    	public bool isDead;
    }

    public class Box
    {
    	public int id;
    	public int typeId;
    	public bool isOpened;
    }

    public class DungeonStatus
    {
    	public long enterAt;
    	public string state;
    	public List<StageInfo> stageProgress = new List<StageInfo>();
    	public StageInfo currentStageInfo;
    	public Npc currentBattleNpc;
    	public List<Npc> killedNpcList = new List<Npc>();
    	public List<Npc> openBoxList = new List<Npc>();
    	public List<Cell> unpickedLoot = new List<Cell>();
    	public List<Cell> lootTotal = new List<Cell>();
    	public uint goldTotal;
    	public uint goldExtTotal;
    	public DungeonAttributeSnapshot attributeSnapshot;
    	public DungeonStageStat stageStat;
    }

    public class OnSaleInfo
    {
    	public long guid;
    	public int goodsId;
    	public int typeId;
    	public uint numTotal;
    	public uint numAvailable;
    	public uint numSQ;
    	public int availableStageId;
    	public uint costGold;
    	public uint costDiamond;
    	public uint discount;
    }

    public class DiamondPrice
    {
    	public int goodsId;
    	public uint num;
    	public uint priceRMB;
    	public uint discount;
    }

    public class OrderInfo
    {
    	public string orderId;
    	public int goodsTypeId;
    	public uint amount;
    	public string payToken;
    	public long tradeSubmitTime;
    	public long tradeDealTime;
    }

    public class PlainCell
    {
    	public int typeId;
    	public uint num;
    }

    public class LocatedCell
    {
    	public int index;
    	public Cell cell;
    }

    public class RankingInfo
    {
    	public int bestStageId;
    }

    public class NoticeInfo
    {
    	public int id;
    	public bool read;
    	public bool confirmed;
    	public bool deleted;
    	public long sendTime;
    	public string title;
    	public string sender;
    	public string content;
    	public uint gold;
    	public uint diamond;
    	public List<Cell> gift = new List<Cell>();
    }

    public class UserNoticeInfo
    {
    	public long uid;
    	public List<NoticeInfo> noticeInfos = new List<NoticeInfo>();
    }

    public class StatInfo
    {
    	public long createTime;
    	public uint loginDaysTotal;
    	public long lastLoginTime;
    	public uint deadTimes;
    	public uint achievementScore;
    	public uint awardItemCount;
    	public uint killMonsterCount;
    	public uint huoDeChengZhuangShu;
    }

    public class ExploreInfo
    {
    	public long lastRefreshChargeTime;
    	public int chargeAvailable;
    	public int chargeTotal;
    	public List<ExploreStatus> status = new List<ExploreStatus>();
    }

    public class ExploreStatus
    {
    	public string characterId;
    	public int heroId;
    	public bool isExploring;
    	public int exploreStageId;
    	public long dispatchedAt;
    	public long completeAt;
    }

    public class PuzzleInfo
    {
    	public int randomSeed;
    	public int total;
    	public int process;
    	public int selected;
    }

    public class DungeonStageStat
    {
    	public int damage;
    	public int healing;
    	public uint kill;
    }

    public class DungeonAttributeSnapshot
    {
    	public uint hp;
    	public uint mp;
    	public uint minAttack;
    	public uint maxAttack;
    	public uint minDef;
    	public uint maxDef;
    	public uint heroLevel;
    	public int gearScore;
    }

    public class DungeonScore
    {
    	public int bestStageId;
    	public int openBoxScore;
    	public int killMonsterScore;
    	public int healthScore;
    	public int gearScore;
    	public int killBossScore;
    	public int awardItemScore;
    	public long timeCost;
    }

    public class DungeonRankingInfo
    {
    	public long uid;
    	public string characterId;
    	public string nickname;
    	public long time;
    	public long date;
    	public int rank;
    	public int chapterId;
    	public DungeonAttributeSnapshot attributeSnapshot;
    	public DungeonStageStat stageStat;
    	public List<Cell> equipments = new List<Cell>();
    	public JobTree jobTree;
    	public long threadId;
    }

    public class PersonalRankingInfo
    {
    	public long uid;
    	public string nickname;
    	public long date;
    	public int rank;
    	public uint gold;
    	public uint kill;
    	public uint achievement;
    	public long threadId;
    }

    public class Comment
    {
    	public long threadId;
    	public long commentId;
    	public long uid;
    	public long date;
    	public string nickname;
    	public int praise;
    	public string content;
    }

    public class OperationActivity
    {
    	public ActivityProcessInfo fisrtPay;
    	public ActivityProcessInfo signInFirst7Day;
    	public ActivityProcessInfo signIn30Day;
    }

    public class ActivityProcessInfo
    {
    	public int process;
    	public long lastGetTime;
    }

}
